#!/bin/bash
mkdir bash c js
touch c/c_is_fun.c
touch js/main.js
touch js/index.js

echo '#!/bin/bash' > bash/alx
echo 'echo "ALX"' >> bash/alx

echo '#!/bin/bash' > bash/school
echo 'echo "School"' >> bash/school